a = range(0, 1001)
b = range(0, 1001)
c = range(0, 1001)
d = range(0, 1001)
a = int(input('Digite um número: '))
b = int(input('Digite um número: '))
c = int(input('Digite um número: '))
d = int(input('Digite um número: '))
((a**b)+(c**d))